blueprint:
  name: Appliance has finished
  description: Do something when an appliance has finished as detected by a power
    sensor and person is home. This is just some small modification of  a blueprint
    created by sbyx. Huge thanks to him. Original source, https://gist.github.com/sbyx/6d8344d3575c9865657ac51915684696
  domain: automation
  input:
    power_sensor:
      name: power_sensor
      description: Power sensor entity (e.g. from a smart plug device).
      selector:
        entity:
          domain:
          - sensor
          multiple: false
    entity_id:
      name: entity_id
      description: person
      selector:
        entity:
          domain:
          - person
          multiple: false
    starting_threshold:
      name: Starting power threshold
      description: Power threshold above which we assume the appliance has started.
      default: 5
      selector:
        number:
          min: 1.0
          max: 1000.0
          unit_of_measurement: W
          mode: slider
          step: 1.0
    starting_hysteresis:
      name: Starting hysteresis
      description: Time duration the power measurement has to stay above the starting
        power threshold.
      default: 5
      selector:
        number:
          min: 0.1
          max: 60.0
          unit_of_measurement: s
          mode: slider
          step: 0.1
    finishing_threshold:
      name: Finishing power threshold
      description: Power threshold below which we assume the appliance has finished.
      default: 5
      selector:
        number:
          min: 1.0
          max: 1000.0
          unit_of_measurement: W
          mode: slider
          step: 1.0
    finishing_hysteresis:
      name: Finishing hysteresis
      description: Time duration the power measurement has to stay below the finishing
        power threshold.
      default: 5
      selector:
        number:
          min: 0.1
          max: 60.0
          unit_of_measurement: s
          mode: slider
          step: 0.1
    actions:
      name: Actions
      description: Actions (e.g. pushing a notification, TTS announcement, ...)
      selector:
        action: {}
  source_url: https://gist.github.com/cmragnar/
trigger:
- platform: numeric_state
  entity_id: !input power_sensor
  for:
    seconds: !input starting_hysteresis
  above: !input starting_threshold
condition:
- condition: state
  entity_id: !input entity_id
  state: home
action:
- wait_for_trigger:
  - platform: numeric_state
    entity_id: !input power_sensor
    below: !input finishing_threshold
    for:
      seconds: !input finishing_hysteresis
- choose: []
  default: !input actions
mode: single
max_exceeded: silent
